import type { Metadata } from "next";

import "./globals.css";
import Nav from "@/compenent/Navbar";

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const geistSans = 'Some value';


export const metadata: Metadata = {
  title: "DYNAMIC ROUTING",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className="bg-slate-300"
     
      
       >
        <Nav/>
       
        {children}
        <footer >
          <div className="footer-content">
        <div className="footer-bottom">
        <p>© 2024 Simple Dynamic Website | Designed by MUHAMMAD QASIM</p>
        </div>
      </div>
      </footer>
      
      </body> 
    </html>
  );
}
